// <auto-generated />
using System;
using Graduation_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Graduation_Project.Migrations
{
    [DbContext(typeof(Db15420Context))]
    [Migration("20250423205643_OrderEdit")]
    partial class OrderEdit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CS_AI")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Graduation_Project.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CustomerId");

                    b.HasIndex(new[] { "UserId" }, "IX_Customers_UserID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Graduation_Project.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("EmployeeId");

                    b.HasIndex(new[] { "UserId" }, "IX_Employees_UserID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Graduation_Project.Models.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HouseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("HouseId");

                    b.HasIndex(new[] { "OwnerId" }, "IX_Houses_OwnerID");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("Graduation_Project.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int")
                        .HasColumnName("HouseID");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId");

                    b.HasIndex("HouseId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Graduation_Project.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OwnerId");

                    b.HasIndex(new[] { "UserId" }, "IX_Owners_UserID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Graduation_Project.Models.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PictureID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PictureId"));

                    b.Property<int>("HousesId")
                        .HasColumnType("int")
                        .HasColumnName("HousesID");

                    b.Property<bool>("Is360")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("URL");

                    b.HasKey("PictureId");

                    b.HasIndex(new[] { "HousesId" }, "IX_Pictures_HousesID");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Graduation_Project.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<int>("HouseId")
                        .HasColumnType("int")
                        .HasColumnName("HouseID");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("ReviewId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_Reviews_CustomerID");

                    b.HasIndex(new[] { "HouseId" }, "IX_Reviews_HouseID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Graduation_Project.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<int>("HouseId")
                        .HasColumnType("int")
                        .HasColumnName("HouseID");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.HasKey("TransactionId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_Transactions_CustomerID");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_Transactions_EmployeeID");

                    b.HasIndex(new[] { "HouseId" }, "IX_Transactions_HouseID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Graduation_Project.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Graduation_Project.Models.Customer", b =>
                {
                    b.HasOne("Graduation_Project.Models.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Graduation_Project.Models.Employee", b =>
                {
                    b.HasOne("Graduation_Project.Models.User", "User")
                        .WithMany("Employees")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Graduation_Project.Models.House", b =>
                {
                    b.HasOne("Graduation_Project.Models.Owner", "Owner")
                        .WithMany("Houses")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Owners_Houses");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Graduation_Project.Models.Order", b =>
                {
                    b.HasOne("Graduation_Project.Models.House", "House")
                        .WithMany("Orders")
                        .HasForeignKey("HouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Houses");

                    b.HasOne("Graduation_Project.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("House");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Graduation_Project.Models.Owner", b =>
                {
                    b.HasOne("Graduation_Project.Models.User", "User")
                        .WithMany("Owners")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Owners_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Graduation_Project.Models.Picture", b =>
                {
                    b.HasOne("Graduation_Project.Models.House", "Houses")
                        .WithMany("Pictures")
                        .HasForeignKey("HousesId")
                        .IsRequired()
                        .HasConstraintName("FK_Houses_Pictures");

                    b.Navigation("Houses");
                });

            modelBuilder.Entity("Graduation_Project.Models.Review", b =>
                {
                    b.HasOne("Graduation_Project.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Customer_Reviews");

                    b.HasOne("Graduation_Project.Models.House", "House")
                        .WithMany("Reviews")
                        .HasForeignKey("HouseId")
                        .IsRequired()
                        .HasConstraintName("FK_House_Reviews");

                    b.Navigation("Customer");

                    b.Navigation("House");
                });

            modelBuilder.Entity("Graduation_Project.Models.Transaction", b =>
                {
                    b.HasOne("Graduation_Project.Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_Transactions");

                    b.HasOne("Graduation_Project.Models.Employee", "Employee")
                        .WithMany("Transactions")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Transactions");

                    b.HasOne("Graduation_Project.Models.House", "House")
                        .WithMany("Transactions")
                        .HasForeignKey("HouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Houses_Transactions");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("House");
                });

            modelBuilder.Entity("Graduation_Project.Models.Customer", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Graduation_Project.Models.Employee", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Graduation_Project.Models.House", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Pictures");

                    b.Navigation("Reviews");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Graduation_Project.Models.Owner", b =>
                {
                    b.Navigation("Houses");
                });

            modelBuilder.Entity("Graduation_Project.Models.User", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Employees");

                    b.Navigation("Orders");

                    b.Navigation("Owners");
                });
#pragma warning restore 612, 618
        }
    }
}
